#!/usr/bin/env python3

"""Capers - play at draughts

This is just a small launcher, the classes themselves are imported
from the capers module.

PORT NOTE: ported from the original PyGTK2 launcher. Requires
Python 3 and PyGObject with the GTK 3 typelib (python3-gi /
PyGObject + gir1.2-gtk-3.0 on most Linux distributions).
"""

import sys
import os
appdir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(1, os.path.join(appdir, 'share'))
import capers

import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)

if __name__ == '__main__':
	main = capers.Main()
